repos:
  # We define a "local" repo of hooks (i.e. commands we want to run).
  - repo: local
    hooks:
      # 1) ESLint
      - id: eslint
        name: ESLint
        entry: npx eslint
        language: system
        pass_filenames: true
        files: \.(js|jsx)$            # Only run on JS files
        stages: [commit]

      # 2) Prettier (format JS, CSS, HTML, etc.)
      - id: prettier
        name: Prettier
        entry: npx prettier --write
        language: system
        pass_filenames: true
        files: \.(js|jsx|css|html)$
        stages: [commit]

      # You can add more hooks here (stylelint, cspell, etc.)
      - id: stylelint
        name: Stylelint
        entry: npx stylelint --fix
        language: system
        pass_filenames: true
        files: \.css$
