repos:
  - repo: local
    hooks:
      # 1) ESLint with React configuration
      - id: eslint
        name: ESLint
        entry: npx eslint
        language: node
        pass_filenames: true
        files: \.(js|jsx)$
        stages: [pre-commit]
        additional_dependencies: [
          'eslint',
          'eslint-plugin-react',
          'eslint-plugin-react-hooks',
          'eslint-config-react-app'
        ]

      # 2) Prettier (already handles React)
      - id: prettier
        name: Prettier
        entry: npx prettier --write
        language: node
        pass_filenames: true
        files: \.(js|jsx|css|html|scss|sass|less)$
        stages: [pre-commit]

      # 3) StyleLint (optional: add CSS-in-JS support)
      - id: stylelint
        name: Stylelint
        entry: npx stylelint --fix
        language: node
        pass_filenames: true
        files: \.(css|scss|sass|less)$
        stages: [pre-commit]
        additional_dependencies: [
          'stylelint',
          'stylelint-config-standard',
          'stylelint-config-prettier',
          'stylelint-config-recommended'
        ]